export const SEARCH_CHARACTERS = "SEARCH_CHARACTERS";
export const GET_CHARACTER = "GET_CHARACTER";
export const CLEAN_CHARACTERS = "CLEAN_CHARACTERS";
export const SET_LOADING = "SET_LOADING";
export const HANDLE_ERROR = "HANDLE_ERROR";
